[template]
exclude = ["public/favicon.ico"]

[values]
dioxus_version = "0.3"

[placeholders.platform]
type = "string"
prompt = "What platform are you targeting?"
choices = ["web", "fullstack", "desktop", "liveview", "tui"]
default = "web"

[placeholders.router]
type = "bool"
prompt = "Should the application use the dioxus router?"
default = true

[conditional.'["fullstack", "liveview"].contains(platform)'.placeholders.backend]
type = "string"
prompt = "What backend framework are you using?"
choices = ["Axum", "warp", "Salvo"]
default = "Axum"

[conditional.'["web", "fullstack", "desktop"].contains(platform)'.placeholders.styling]
type = "string"
prompt = "How do you want to create CSS?"
choices = ["Tailwind", "Vanilla"]
default = "Vanilla"

[conditional.'["liveview", "tui"].contains(platform)']
ignore = [ "tailwind.config.js", "input.css", "public" ]
[conditional.'platform == "desktop"']
ignore = [ "public" ]
[conditional.'styling == "Vanilla"']
ignore = [ "tailwind.config.js", "input.css", "public/tailwind.css" ]
