name: Templates CI

on:
  push:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]


# workflow_dispatch:
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always
  RUSTFLAGS: -D warnings

jobs:
  check:
    if: github.event.pull_request.draft == false
    name: Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - uses: cargo-bins/cargo-binstall@v1.10.13
      - run: cargo binstall dioxus-cli@0.6.0-alpha.5
      - run: sudo apt install expect libwebkit2gtk-4.1-dev build-essential curl wget file libxdo-dev libssl-dev libayatana-appindicator3-dev librsvg2-dev
      #libgtk-3-dev libsoup-3.0-dev libjavascriptcoregtk-4.1-dev

      # Test bare bones
      - run: expect ./scripts/generate-barebones-all.exp
      - name: Test Bare-Bones
        working-directory: ./barebones-all
        run: cargo check

      # Test jumpstart
      - run: expect ./scripts/generate-jumpstart-all.exp
      - name: Test Jumpstart
        working-directory: ./jumpstart-all
        run: cargo check

      # Test workspace
      - run: expect ./scripts/generate-workspace-all.exp
      - name: Test Workspace
        working-directory: ./workspace-all
        run: cargo check
      

            
