[template]

[placeholders]

styling = { prompt = "How do you want to create CSS?", choices = [
    "Tailwind",
    "Vanilla",
], default = "Vanilla", type = "string" }

[conditional.'styling == "Vanilla"']
ignore = ["tailwind.config.js", "input.css"]